# Generated by Django 5.0.7 on 2024-07-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_rename_test_quiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='test',
            new_name='quiz',
        ),
    ]
